### ISSUE TITLE
Parser should ignore invalid headers

### ISSUE THREAD

**Issue by zdm** [kazuho/p5-http-parser-xs#10]
Hi.

Incapsula anti-ddos protection service return invalid headers as part of anti-ddos protection:
For example:

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
X-Row-Count: 1
X-Varnish: 28002913
Age: 0
Via: 1.1 varnish-v4
Accept-Ranges: bytes
X-BackendHost: 10.10.29.62
Accept-Ranges: bytes
Date: Mon, 18 Jul 2016 17:16:36 GMT
X-Varnish: 462646394
Age: 0
Via: 1.1 varnish
Connection: keep-alive
X-AccessID: mozscape-e5255cb56a
X-UnknownAPI:
X-Throttled: 0
X-ExpiredSignature: 0
X-AuthenticationError: 0
Set-Cookie: visid_incap_149733=9RLkJc7RRi2PkVPIN06FsvEOjVcAAAAAQUIPAAAAAADYj7vGzAU5JpqKZo/QhxMS; expires=Tue, 18 Jul 2017 15:26:52 GMT; path=/; Domain=.seomoz.com
Set-Cookie: incap_ses_408_149733=09HITSsAilhWj/CPFYKpBfEOjVcAAAAAa5NTadmKGNFtXOGIW6qHbg==; path=/; Domain=.seomoz.com
Set-Cookie: ___utmvmXvuOVmF=gLNAmvbZcpy; path=/; Max-Age=900
Set-Cookie: ___utmvaXvuOVmF=DeifNxR; path=/; Max-Age=900
Set-Cookie: ___utmvbXvuOVmF=iZK
    XSaOzalA: ctu; path=/; Max-Age=900
X-Iinfo: 0-14477114-14477115 NNNN CT(117 -1 0) RT(1468862193272 1) q(0 0 1 -1) r(3 3) U5
X-CDN: Incapsula
Content-Encoding: gzip
Transfer-Encoding: chunked

```

Last Set-Cookie header is invalid, because it contains extra line break.

Is it possible to make parser ignore only such invalid headers?
Currently parser return -1 and no headers were parsed at all.

**Comment by zdm** [comment]
Or maybe this is because overall headers length > 1 Kb?
Is it possible to increase max. headers length limit?

**Comment by kazuho** [comment]
A header lines spanning into multiple lines was deprecated in [RFC 7230](https://tools.ietf.org/html/rfc7230) but is still allowed. Quoting from A.2:

```
Header fields that span multiple lines ("line folding") are
deprecated.  (Section 3.2.4).
```

**Comment by zdm** [comment]
Yes, I know, that they are deprecated, but they are still used.

Also, I found, that parser return nothing, if one of the headers
contains forbidden character, for example "\x01". Is it possible to
ignore only this header, not everything?

**Comment by miyagawa** [comment]
> Yes, I know, that they are deprecated, but they are still used.

They are still used and allowed. You are mistaken that it is not supported.

I tried your example with `parse_http_response` function of the module and it is returning a successful parsed result for me.

**Comment by miyagawa** [comment]
>  that parser return nothing, if one of the headers contains forbidden character, for example "\x01". Is it possible to ignore only this header, not everything?

While I cannot reproduce the failure, if a header body contains forbidden characters, the parser should just fail. There're only valid HTTP headers and invalid HTTP headers, and no "partially valid HTTP headers".

You might want to try other modules that might be tolerating such invalid HTTP headers, at the expense of being incorrect.

**Comment by zdm** [comment]
1. Yes, parser returns wrapped headers, but with single mistake:

For example, for original header:
```
AAA: 123
    456
```

it should return:
```
'AAA', '123    456'
```
but it return
```
'AAA', "123\n    456" # extra "\n"
```

2. Second error:
If header contains forbidden character, for example "\x01" - parser
return nothing. But, it should just ignore this corrupted header and
parse the rest. At least browsers do so.

**Comment by zdm** [comment]
I created this issue, because parser not works with well - known cdn and
anti-ddos service incapsula.com.

You can implement tolerant mode if you want, I already created and use
fallback routine.

Thank you.

**Comment by miyagawa** [comment]
you should report the service about it and fix the invalid response - that would be for the better. I think this issue can be closed.

**Comment by zdm** [comment]
Seems, that this is a part of anti-ddos solution.

**Comment by miyagawa** [comment]
ha! so clients will receive that invalid headers and stop ongoing requests? Seems the protection is working then :p

**Comment by zdm** [comment]
Yes, that's funny, but i have no other answer - why they are use this
deprecated and corrupted headers?

And this solution works in browsers, but may not work with third - party
headers parsers, that can be used in botnet.

**Comment by kazuho** [comment]
@zdm 
> Yes, parser returns wrapped headers, but with single mistake:
> 
> For example, for original header:
> ```
> AAA: 123
>     456
> ```
> 
> it should return:
> ```
> 'AAA', '123    456'
> ```
> but it return
> ```
> 'AAA', "123\n    456" # extra "\n"
> ```

I do not have a strong preference on this.

Until now, picohttpparser (which runs below HTTP::Parser::XS) has always preserved `\n`, since an application _might_ want to know if `\n` is used.

However, since RFC 2616 section 4.2 states, quote:
```
Any LWS
that occurs between field-content MAY be replaced with a single SP
before interpreting the field value or forwarding the message
downstream.
```
it is true that a parser is allowed to rewrite consecutive LWS into a single SP which would not be a difficult thing to do (either within picohttpparser or HTTP::Parser::XS), and expect _not_ to break existing applications.

> If header contains forbidden character, for example "\x01" - parser
> return nothing. But, it should just ignore this corrupted header and
> parse the rest. At least browsers do so.

Interesting. However I am a bit afraid changing the behavior as such might cause issues for HTTP::Parser::XS / picohttpparser.

As an example, consider the case where you receive a connection header with its value set to "\x01". As a HTTP client implementer, I would not want to reuse such connection for future requests. In other words, I would like to handle the case as if `connection: close` was received. However, if we start dropping broken headers, the client would continue reusing the connection, since the absence of the connection header implies keep-alive.

**Comment by zdm** [comment]
yes, your evidence has sense.
thank you.

**Comment by korenyoni** [comment]
Not trying to revive an ancient issue, but maybe this will help someone running into this issue with Imperva (aka Incapsula). I've talked to Imperva support (they even gave me permission to relay this information publicly), but some of these invalid or problematic headers have to do with their techniques in classifying user-agents. That is, they send somewhat problematic headers (I believe `Set-Cookie` may be one of them) to see how the user-agent behaves. In most cases (browsers) nothing happens. But here in nodejs there is an issue. Anyways, you can request them to disable this behavior. Hope this helps.
