### ISSUE TITLE
HTTP::Parser::XS::PP::_parse_as_hashref does not set special_headers

### ISSUE THREAD

**Issue by makamaka** [kazuho/p5-http-parser-xs#11]
In HTTP::Parser::XS::PP::_parse_as_hashref, special_headers is not set with parsed values.
I wrote the patch.
https://github.com/makamaka/http-parser-xs/commit/e60a0429de6051dbefa77965ebf3112a0e8bb7d9

**Comment by kazuho** [comment]
LGTM. Can you please file a PR?
